### ISSUE TITLE
Put "Why?" section in README.md

### ISSUE THREAD

**Issue by kuy** [kuy/redux-tooltip#18]
Because there are lots of similar tooltip components, I have to explain why `redux-tooltip' is needed to me.

**Comment by oyeanuj** [comment]
Yes, please! I'd love to understand this better :)

**Comment by kuy** [comment]
Do you have an interest in this tooltip component? 😃 

What I needed is to move all tooltip states to Redux's store for controlling tooltips completely.
Other libraries keep the state of tooltip as a local state. It's not a big problem in most cases, but when I want to implement [delayed/keep tooltip](http://kuy.github.io/redux-tooltip/) and other complicated features, I feel I can't.
Of course, I could send Pull Request to add lots of specific features to them, but I need something like low-level API or mechanism for future development (I can't expect what features I need).

Any questions are welcomed 😃

**Comment by oyeanuj** [comment]
Got it, thanks for the context.

I am looking to use tooltips in form validation (with Redux-Form) and want to be able to show tooltip on the submit button when there is a validation error (like pasted below). To do that, I need to be able to programmatically launch the tooltips (and have them fade away). 

<img width="429" alt="screen shot 2016-08-31 at 4 39 08 pm" src="https://cloud.githubusercontent.com/assets/9633371/18187250/df879648-705c-11e6-9704-0cfc8686145f.png">


Does this library allow me to programmatically launch the tooltips?

**Comment by kuy** [comment]
@oyeanuj Sorry for late replying. You can show tooltips programmatically. For beginners, we provide `<Origin>` component, but you can also Redux's action to control tooltips.

Remote demo: http://kuy.github.io/redux-tooltip/remote.html
Remote source code: https://github.com/kuy/redux-tooltip/blob/master/examples/remote/app.js

**Comment by kuy** [comment]
I added "Why?" section, so I close this issue but I can feel free to ask me about usage here 👍

**Comment by oyeanuj** [comment]
@kuy Couple of more questions.

1. What is the best way to hide the tooltip on click anywhere on the page? Once the tooltip is displayed, I would like it to close if a user clicks elsewhere on the page. 

2. Do you plan to keep it at feature-parity with react-tooltip?

**Comment by kuy** [comment]
@oyeanuj I try to answer.

1. It cannot be done by only redux-tooltip. I'm using [react-onclickoutside](https://github.com/Pomax/react-onclickoutside) to detect clicks elsewhere on the page.
2. No, at this time. For example, which feature you want to bring from react-tooltip to redux-tooltip? I can't promise I implement your request, but I want to know.

**Comment by oyeanuj** [comment]
thanks for the answers!

1. > It cannot be done by only redux-tooltip. I'm using react-onclickoutside to detect clicks elsewhere on the page.

Can you share any example or code snippet with react-onclickoutside?

2. > I can't promise I implement your request, but I want to know.

I was just curious since you mentioned you started there!

**Comment by kuy** [comment]
> Can you share any example or code snippet with react-onclickoutside?

Okay, I'll add it to "remote" example later!

> I was just curious since you mentioned you started there!

Ah, okay. I have a plan to add "offset", tooltip animation, and theme feature. The problem is that these features don't have high priority in my day work 😜

**Comment by oyeanuj** [comment]
> Okay, I'll add it to "remote" example later!

Great, any timeline on this? Just asking to plan my work a little bit :)

**Comment by kuy** [comment]
It's time to use Project feature ✨  https://github.com/kuy/redux-tooltip/projects/1

First, I want to release version `0.7.1` that includes a commit to reducing file size of the library. I removed `redux-actions` from dependencies. After `0.7.1`, I'll start to developing Theme feature. It is the road to 1.0 release.

**Comment by kuy** [comment]
@oyeanuj  Maybe I need your help to write API documentation for `1.0` release. When I prepare the base for docs (I want to try [ESDoc](https://esdoc.org/)), I'll mention you on GitHub.

**Comment by oyeanuj** [comment]
@kuy, yes, i'd be happy to help as and when I get some time!
