### ISSUE TITLE
When using react 15 arrows on tooltips disappear

### ISSUE THREAD

**Issue by gtoma4** [kuy/redux-tooltip#25]
@kuy - I found that the !important declaration appears to be ignored and the incorrect style is applied to the arrow. (the transparent borders are not styled since the themed bordercolor is applied).  I addressed the issue in my forked version (github.com/gtoma4/redux-tooltip) but I think there is a better way to do it...

**Comment by kuy** [comment]
Hi @gtoma4, I'm very sorry I couldn't respond your questions and thank you for working on my library. I'd like to merge your works on [the fork](https://github.com/gtoma4/redux-tooltip).
First, I will update dependencies. I hope you send PRs to resolve pending issues.

**Comment by dyarkovoy** [comment]
Hi @kuy, it would be great if you could merge the fix into the main branch.
