### ISSUE TITLE
add div selectors

### ISSUE THREAD

**Issue by albreax** [kuy/redux-tooltip#32]
I integrated redux-tooltip. It works very well. However I have different styling-requests. Please add IDs to select the Divs.

**Comment by albreax** [comment]
@kuy That would be great!

**Comment by kuy** [comment]
@albreax Hi, I've just released [v0.7.0](https://github.com/kuy/redux-tooltip/releases/tag/v0.7.0). Please check out [style example](https://github.com/kuy/redux-tooltip/tree/master/examples/style).
