### ISSUE TITLE
Enable Redux Devtools on examples

### ISSUE THREAD

**Issue by oyeanuj** [kuy/redux-tooltip#38]
Hi @kuy! I was looking to understand how the library works, and was wondering if it would be possible to enable DevTools on those examples? 

It would help developers see how the actions lead to particular state changes.

Thank you!

**Comment by kuy** [comment]
Thanks for your proposal! Do you have a plan to send PR for this? I'm welcome your contribution 😃

**Comment by oyeanuj** [comment]
Done, #39 :)

**Comment by kuy** [comment]
@oyeanuj  Now Redux DevTools extension works on demo page!
http://kuy.github.io/redux-tooltip/
