### ISSUE TITLE
`auto` prop on `<Origin>` produces "Unknown prop" React error

### ISSUE THREAD

**Issue by bkrem** [kuy/redux-tooltip#42]
Currently, passing an `auto` prop to `<Origin>` as suggested in the documentation (a prop for both `<Tooltip>` & `<Origin>`) produces the following React "unknown prop" error:
```
Warning: Unknown prop `auto` on <span> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in span (created by Origin)
    in Origin (created by Connect(Origin))
```

From looking over [origin.js](https://github.com/kuy/redux-tooltip/blob/master/src/origin.js), this seems to be due to the `auto` prop not being blacklisted or used.

I'd suggest two ways to move forward here:
1. Remove `auto` from `Origin`'s props in the documentation, since it isn't actually being used.
2. Blacklist `auto` for later use.

I'm happy to write a PR for either, let me know what you'd like to do here :)

**Comment by kuy** [comment]
@bkrem Nice catch. This is a mistake in the documentation. So I choose the first one in your suggestions. Thanks!
