### ISSUE TITLE
React 16 support?

### ISSUE THREAD

**Issue by AshCoolman** [kuy/redux-tooltip#78]
I am experimenting with this project. To get a simple setup to run I had to do the following:

```
import PT from 'prop-types';

React.PropTypes = PT;
```

I can't find any discussion about React 16 support and I was wondering what the support/intended support is?

Thanks

**Comment by qmmr** [comment]
Just found that I couldn't use `redux-tooltip` with React 16 if I didn't use the technique suggested by @AshCoolman 
Are there any plans on deprecating `PropTypes`?

**Comment by Bradleykingz** [comment]
Finally updated c33168c
