### ISSUE TITLE
Want to be one of the maintainers.

### ISSUE THREAD

**Issue by wamujlb** [kuy/redux-tooltip#88]
Hi @kuy ,

I want to be one of the maintainers of this project. Already added some new props and fixed some bugs in my fork. If you have some time we can talk about it. Please write to my email: shamil.mammadof@gmail.com

**Comment by dainmiller** [comment]
Ditto.

**Comment by kuy** [comment]
@wamujlb @dainmiller  Very sorry, I didn't noticed this issue. I'll add you guys as collaborators.

**Comment by kuy** [comment]
I also need to add you in NPM. Please tell me your username on NPM.

**Comment by Bradleykingz** [comment]
If you still need maintainers, I'm @bradleykingz on NPM, too

**Comment by kuy** [comment]
@Bradleykingz Thank you! I added you both github and npm.
